# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226c47cca5dd24bcc4ad68978f16dd8b4281e71d87d58ec69aeb27fa95bce1dea657d5f717b630d112449ca6e07b7b27e43b1d4fad52a0b7dbf5329e5d30277e

test:
  secret_key_base: 23cacac412f52a5a43a138877f0b104241a6234535eb1cf0ce0d7ee527b14cb57848c146dfb25018e2fa4127204d74f34b2b20f50db20f9f0fb08549a6fa38ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
